Creation of initial Specification and Checks prototype
CIHDigitalConfigurator/CIH_Toolkit pull request #2
Opened 2021-01-14 16:43 UTC by alelom

2021-01-14 19:03 UTC, al-fisher commented
@alelom This is looking good - will have a bit more of a play with it tomorrow. 😸 

Initial comment around the handling of the Boolean operators -

Structured so as to accept a `List<IFilter>` and an `enum` in this way does leave the door open to some ambiguity for some of the operators.
For instance an `IMPLIES` must only have two arguments and is not a commutative operator, and so both the number and order of the inputs matters. You can create the below which is not clear

![image](https://user-images.githubusercontent.com/15924573/104635806-540ca800-569a-11eb-991e-b8976f8d6701.png)



might therefore be easier to design as discrete objects and properties? What do you think?

2021-01-14 20:31 UTC, al-fisher commented
Thinking further on the formatting of above _could_ be good to also think about structure of concepts for reflection into Excel_Toolkit! 

Building specs in tabular format through Excel templates will be very powerful.
Noting here - but perhaps one for later iterations

2021-01-15 09:19 UTC, alelom commented
> For instance an IMPLIES must only have two arguments and is not a commutative operator, and so both the number and order of the inputs matters. You can create the below which is not clear

I see what you mean, but I think it is not different from any other operator, as they are all defined for 2 inputs only. The IMPLIES may simply work so if more than 2 inputs are defined e.g. A, B, C, D they resolve as [(A => B) => C] => D. Only difference as you say is that they are commutative, and in this the list order is important – however the user has still full control. Plus, it's less common as an operator, and I included it only for completeness. Happy to chat.

2021-01-15 17:52 UTC, alelom commented
While implementing checks: the concept of as in our [Domain class](https://github.com/BHoM/BHoM/blob/ba4e0bddcf8bb86497b2e10f1663ab2f31319217/Data_oM/Collections/Domain.cs) may be too restrictive. Common scenario can be a Domain check for e.g. DateTime. I'm implementing it with System.Object. Only requirement for the check to work is that the type implements the `>`, `<`, `==` operators (as DateTime does). This way it is extendable to any measurable quantity. Happy to discuss.

2021-01-18 15:36 UTC, al-fisher commented on CIH_Engine/CIH_Engine.csproj
> +      <HintPath>..\..\..\..\..\ProgramData\BHoM\Assemblies\BHoM.dll</HintPath>
```suggestion
      <HintPath>C:\ProgramData\BHoM\Assemblies\BHoM.dll</HintPath>
```

2021-01-18 15:36 UTC, al-fisher commented on CIH_Engine/CIH_Engine.csproj
> +      <HintPath>..\..\BHoM_Engine\Build\Reflection_Engine.dll</HintPath>
```suggestion
      <HintPath>C:\ProgramData\BHoM\Assemblies\Reflection_Engine.dll</HintPath>
```

2021-01-18 15:38 UTC, al-fisher commented
@alelom Added a couple of comments 👆 👆  in the absence of BHoMBot 🤖 
😄

2021-01-21 12:29 UTC, al-fisher commented on CIH_oM/Conditions/ValueInSet.cs
> +        List<object> Set { get; set; }
```suggestion
        public virtual List<object> Set { get; set; }
```

@alelom missing `public virtual` here

2021-01-21 14:14 UTC, al-fisher requested changes
Hey @alelom - this is looking really good! Great stuff

I have a few comments will capture as I think of them ... I am continuing to experiment with and test

First comment is around the structuring of the nested `Conditions` (`Value`/`ValueInDomain`/_etc.)  being owned as a discrete property of the `PropertyCondition`

![image](https://user-images.githubusercontent.com/15924573/105359590-86b12600-5bef-11eb-8cec-57344fbbf8d6.png)

This leads to the above - which I think as a couple of issues for the user. 

- The `PropertyName` the Condition applies to should I think be defined "Flat" in parallel with the actual `Value`, `Tolerance`, `Domain` etc. Think this is a more logical structure for the user - see original prototype in issue here: https://github.com/CIHDigitalConfigurator/CIH_Toolkit/issues/1
We don't want the two separating. 
- Additionally having it structured as is currently you end up with the Parent `Source` and `Comment` being duplicated at both levels as your above example.

This structure comes from, I presume, wanting to reuse the Conditions across the `PropertyCondition`, `CustomDataCondition`, and `FragmentCondition` right?

I might simplify this by putting the `PropertyName` on the Value/Domain etc. Conditions themselves as a simple `string` property to start with. This help link more directly the Reference Value to the PropertyName etc. 
This simple approach will work for both Properties and Custom Data anyway. Is just Fragments that are different. Which is worth perhaps a discussion if they need more thought

Happy to chat on the above - will continue testing

2021-01-21 14:41 UTC, alelom commented
> The PropertyName the Condition applies to should I think be defined "Flat" in parallel with the actual Value, Tolerance, Domain etc. Think this is a more logical structure for the user - see original prototype in issue here: #1
We don't want the two separating.

That was actually my first prototype. I then moved away from that because, in order to cover all _"comparisons"_ (`Value`, `Domain` and `Set`) you end up having:
- 3"CustomData" conditions objects: `CustomDataValueCondition`, `CustomDataDomainCondition`, `CustomDataSetCondition`
- 3"Fragments" conditions objects, like the above,
- 3"Property" conditions objects, like the above.

Therefore, I refactored, thinking that this approach:
- Makes the life actually easier for the user (less components to search; easier to switch)
- Makes things more scalable, as I thought that more conditions where those "comparisons" could be attached to may appear in the future. 

However, I did realise that, as you say, there is repetition of Source and Comment at the two levels. 
To solve that, I had in mind to perhaps qualify `ValueCondition`, `DomainCondition` and `SetCondition` as "Comparisons" instead (`ValueComparison`, `DomainComparison`, `SetComparison`) – objects that acquire value only when attached to a parent condition.

2021-01-21 18:30 UTC, al-fisher commented
Hey @alelom - just capturing our conversation earlier.

Suggested moving back to list of simple Conditions
`ValueCondition`
`DomainCondition`
`SetCondition`
etc.

All the above then have as a defining Property: `string PropertyName` that the Condition applies to.

This PropertyName can refer to an object's _Defining Property_, _Derived Property_, _Custom Data_, or _Property of a Fragment_ it does not matter. This is all handled in your GetValue method.

This negates the need for `PropertyCondition`, `CustomDataCondition`, `FragmentCondition` layer


Also means we can neatly implement exposure of Reflection of Engine methods for applying Conditions to Properties like `Length()` etc. very intuitively for users.

2021-01-21 18:31 UTC, al-fisher commented
Think above captures it? 

Can also catch up and finish our chat on Specifications owning Specifications as needed ... 😄

2021-01-25 11:59 UTC, alelom commented on CIH_Engine/Compute/ApplyCondition/ApplyDomainCondition.cs
> +            if (true) // TODO: implement extremes.
To be done. Quick feature for another PR. We need to merge https://github.com/BHoM/BHoM/pull/1165 for this.

2021-01-25 18:48 UTC, al-fisher commented on CIH_Engine/Compute/ApplyCondition/ApplyValueCondition.cs
> +                                passed = numericalValue > referenceNumValue + numTolerance;
```suggestion
                                passed = numericalValue >= referenceNumValue - numTolerance;
                                break;
                            case (ValueComparisons.LargerThan):
                                passed = numericalValue > referenceNumValue - numTolerance;
```

2021-01-25 19:02 UTC, al-fisher requested changes
Hi @alelom 
Have tested and workflow is I think now looking good.

A couple of issues - some I think we need to look at here on this PR together before merge. Others are just questions/suggestions that can be picked up later.

- Issue with tolerance being applied correctly for `GreaterThan` cases - see suggest commit for application if you agree

- Value Check IsEqual not working as expected for Strings
![image](https://user-images.githubusercontent.com/15924573/105752176-d9b41180-5f3e-11eb-81cd-343a9533ee8e.png)

- Properties in CustomData are not being compared properly it seems
![image](https://user-images.githubusercontent.com/15924573/105752852-b6d62d00-5f3f-11eb-865b-a1ce2bf1a181.png)

Examples above saved in folder along with your example

2021-01-25 19:04 UTC, al-fisher commented on CIH_Engine/Compute/ApplyCondition/ApplyValueCondition.cs
> +                                passed = numericalValue > referenceNumValue + numTolerance;
Suggested commit above

2021-01-26 10:08 UTC, alelom commented
@al-fisher thanks for spotting those, all fixed now.

2021-01-26 10:35 UTC, al-fisher commented
Brilliant - thanks

2021-01-26 11:28 UTC, al-fisher approved these changes
Thanks @alelom 

This is looking great as first prototype now. Will approve and merge to continue to dev as new issues 

Cheers

2021-01-26 11:29 UTC, merged